version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: netflixripoff-mariadb
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword123!
      MYSQL_DATABASE: netflixripoff
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: netflixripoff-phpmyadmin
    platform: linux/amd64
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: P@ssword123!
    depends_on:
      - mariadb

  laravel:
    build:
      context: .
      dockerfile: ./netflixRipOff/Dockerfile
    container_name: netflixripoff-laravel
    platform: linux/amd64
    environment:
      DB_HOST: mariadb
      DB_DATABASE: netflixripoff
      DB_USERNAME: root
      DB_PASSWORD: P@ssword123!
    ports:
      - "8000:8000"
    volumes:
      - ./netflixRipOff:/var/www/html:z
    command: >
      sh /var/www/html/entrypoint.sh

volumes:
  mariadb-data:
