services:
  db:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql

  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html           
      - ./.env:/var/www/.env                
    environment:                          
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  vuejs:
    build:
      context: ./frontend
    container_name: vue-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    command: npm run serve

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db-data:
