services:
  sql-generator:
    image: alpine:latest
    container_name: sql-generator
    volumes:
      - ./db-init:/db-init:z  # Make sure the db-init folder is correctly mapped
    working_dir: /app  # Working directory should be /app as you are running scripts from there
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    entrypoint: /bin/sh -c "apk update && apk add gettext && echo 'Running SQL generation script...'; /db-init/generate-sql.sh; echo 'SQL file generated successfully!';" 

  mariadb:
    image: mariadb:10.11 
    depends_on:
      - sql-generator
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    volumes:
      - mariadb-data:/var/lib/mysql:z # Added :z for SELinux compatibility
      - ./db-init/sql-file:/docker-entrypoint-initdb.d:z

  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html:z  # Corrected with :z
      - ./.env:/var/www/.env:z     # Corrected with :z
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  vuejs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app:z         # Corrected with :z
      - /app/node_modules         # No :z needed since this is an internal container directory
    command: npm run serve

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
    ports:
      - "8081:80"
    depends_on:
      - mariadb

volumes:
  mariadb-data:
