version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: netflixripoff-mariadb
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: netflixripoff-phpmyadmin
    platform: linux/amd64
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mariadb

  laravel:
    build:
      context: .
      dockerfile: ./netflixRipOff/Dockerfile
    container_name: netflixripoff-laravel
    platform: linux/amd64
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - ./netflixRipOff:/var/www/html:z
    depends_on:
      - mariadb
    command: >
      sh -c "/var/www/html/wait-for-it.sh mariadb:3306 -- /var/www/html/entrypoint.sh"

volumes:
  mariadb-data:
