CREATE USER IF NOT EXISTS 'senior'@'%' IDENTIFIED BY 'seniorpassword';
GRANT SELECT, INSERT, UPDATE, DELETE, INDEX, LOCK TABLES, CREATE TEMPORARY TABLES, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON netflixripoff.* TO 'senior'@'%';
GRANT CREATE USER, RELOAD ON *.* TO 'senior'@'%';
GRANT SELECT ON mysql.user TO 'senior'@'%';

CREATE USER IF NOT EXISTS 'medior'@'%' IDENTIFIED BY 'mediorpassword';
GRANT SELECT, INSERT, UPDATE, DELETE, INDEX, LOCK TABLES, CREATE TEMPORARY TABLES, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON netflixripoff.* TO 'medior'@'%';
GRANT CREATE USER, RELOAD ON *.* TO 'medior'@'%';

CREATE USER IF NOT EXISTS 'junior'@'%' IDENTIFIED BY 'juniorpassword';
GRANT SELECT, INSERT, UPDATE, DELETE, INDEX, LOCK TABLES, CREATE TEMPORARY TABLES, SHOW VIEW, EXECUTE ON netflixripoff.* TO 'junior'@'%';

CREATE USER IF NOT EXISTS 'Senior'@'%' IDENTIFIED BY 'P@ssword123';
GRANT EXECUTE, SELECT ON netflixripoff.* TO 'Senior'@'%';
GRANT RELOAD ON *.* TO 'Senior'@'%';

CREATE USER 'setup_user'@'%' IDENTIFIED BY 'setup!';
GRANT ALL PRIVILEGES ON *.* TO 'setup_user'@'%';
GRANT GRANT OPTION ON *.* TO 'setup_user'@'%';
FLUSH PRIVILEGES;

DROP USER IF EXISTS 'root'@'localhost';
DROP USER IF EXISTS 'root'@'%';

FLUSH PRIVILEGES;
